# Generated by Django 6.0.5 on 2026-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='rows',
            new_name='row',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'order', 'row', 'seat'), name='unique_ticket'),
        ),
    ]
